# Generated by Django 2.2.5 on 2019-10-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20191025_1903'),
        ('app_1', '0002_auto_20191024_2255'),
    ]

    operations = [
    ]
